remote_theme: pmarsceill/just-the-docs
logo: img/logo.svg
ga_tracking: UA-23493957-4
ga_publisher: pub-3600741293730423
title: VueGL
description: Vue.js components rendering 3D graphics reactively via Three.js
aux_links:
  View project on GitHub: //github.com/vue-gl/vue-gl
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: examples
    values:
      layout: example
      nav_exclude: true
      no_ads: true
exclude:
  - rollup.config.js
